### ISSUE TITLE
Add absolute pooling

### ISSUE THREAD

**Issue by brohrer** [brohrer/sharpened-cosine-similarity#1]
Debug and test a maximum magnitude pooling layer

@StephenHogg wrote a nice looking bit of code for this, but I haven't been able to get it to work just yet.

Original code
https://github.com/StephenHogg/SCS/blob/main/SCS/layer.py

Copy/pasted to
https://github.com/brohrer/sharpened_cosine_similarity_torch/blob/main/absolute_pooling.py

**Comment by StephenHogg** [comment]
Potentially the problem is in the lines that call `partial`, try it without actually specifying the argument name

**Comment by StephenHogg** [comment]
Yeah that's what you need to do. I didn't see it because I was naming all my arguments

**Comment by brohrer** [comment]
Thanks! I have it working now. I'll get it checked in and close this.
