### ISSUE TITLE
Reimplmentation & slight improvements.

### ISSUE THREAD

**Issue by hukkelas** [brohrer/sharpened-cosine-similarity#7]
Hi!
I played around with your code yesterday and ended up refactoring it quite heavy to ease usage. The code is nowhere ready for any pull request, but I hope that you find the changes somewhat useful.

You can find the code [here](https://github.com/hukkelas/sharpened_cosine_similarity_torch).

Notes:
- I were able to achieve 91.3% CIFAR-10 accuracy with a model of 1.2M parameters( [see here for model implementation](https://github.com/hukkelas/sharpened_cosine_similarity_torch/blob/ce45cf9718d515b3a875e3fd85b39d0740bc19b1/train.py#L84)).
- Residual connections seem to somewhat help deeper networks, however, training a much deeper model does not work out of the box ([see here for implementation](https://github.com/hukkelas/sharpened_cosine_similarity_torch/blob/ce45cf9718d515b3a875e3fd85b39d0740bc19b1/train.py#L85)).
- Either annotating the forward pass of the SCS layer or [scripting the model](https://github.com/hukkelas/sharpened_cosine_similarity_torch/blob/ce45cf9718d515b3a875e3fd85b39d0740bc19b1/train.py#L99) will improve runtime at least 30% (measured on NVIDIA 1060 GPU).

The code automatically uses a CUDA capable device if available, is quite cleaner than the original training script and will hopefully help you iterate on the idea :) 

You can view the tensorboard logs of my experiments here:
https://tensorboard.dev/experiment/AY27LbxrRpaBHNMO0m9Wkw/#scalars

**Comment by brohrer** [comment]
Thanks for spending so much attention on this! I'm looking forward to combing through your code.
91.3% on CIFAR-10 is definitely a high water mark so far.
